### ISSUE TITLE
NPE when opening empty Yang file.

### ISSUE THREAD

**Issue by AlexTugarev** [yang-tools/yang-lsp#64]
Open empty Yang file with vscode extension for Yang.

See exception is logged:
```
[Error - 12:09:57] java.lang.IllegalStateException: getReferenceDescriptions file:///Users/tugarev/Desktop/test2.yang
Aug 09, 2017 12:09:57 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint lambda$static$0
SEVERE: Internal error: java.lang.NullPointerException
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$null$0(RequestManager.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at io.typefox.yang.scoping.ScopeContextProvider$Adapter.findInEmfObject(ScopeContextProvider.java:111)
	at io.typefox.yang.scoping.ScopeContextProvider.getScopeContext(ScopeContextProvider.java:218)
	at io.typefox.yang.ide.symbols.YangDocumentSymbolService.getSymbols(YangDocumentSymbolService.java:64)
	at org.eclipse.xtext.ide.server.symbol.DocumentSymbolService.getSymbols(DocumentSymbolService.java:160)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$null$31(LanguageServerImpl.java:560)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:284)
	at org.eclipse.xtext.ide.server.LanguageServerImpl.lambda$documentSymbol$32(LanguageServerImpl.java:562)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$null$0(RequestManager.java:78)
	... 4 more

[Error - 12:09:57] Request textDocument/documentSymbol failed.
  Message: Internal error, please look at the server's logs.
  Code: -32603 
```

**Comment by AlexTugarev** [comment]
The logged error could be a separate issue, as it is repeatedly logged on save or load of file containing a minimal module from template.
