### ISSUE TITLE
NPE in diagram generator

### ISSUE THREAD

**Issue by spoenemann** [yang-tools/yang-lsp#69]
* Open `example-3-a.yang`
 * Double-click on `example-3-suba`

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$null$0(RequestManager.java:84)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at io.typefox.yang.diagram.YangDiagramGenerator.createEdge(YangDiagramGenerator.java:771)
	at io.typefox.yang.diagram.YangDiagramGenerator.lambda$13(YangDiagramGenerator.java:496)
	at io.typefox.yang.diagram.YangDiagramGenerator.lambda$24(YangDiagramGenerator.java:1003)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at io.typefox.yang.diagram.YangDiagramGenerator.postProcessing(YangDiagramGenerator.java:1005)
	at io.typefox.yang.diagram.YangDiagramGenerator.generateDiagram(YangDiagramGenerator.java:169)
	at io.typefox.yang.diagram.YangDiagramGenerator.generate(YangDiagramGenerator.java:136)
	at io.typefox.sprotty.server.xtext.DiagramLanguageServerExtension.lambda$updateDiagram$10(DiagramLanguageServerExtension.java:226)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$null$0(LanguageServerImpl.java:943)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:284)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$doRead$1(LanguageServerImpl.java:945)
	at org.eclipse.xtext.ide.server.concurrent.RequestManager.lambda$null$0(RequestManager.java:78)
	... 4 more
```

**Comment by JanKoehnlein** [comment]
Fixed. There is a dangling import which is now show as a node with label 'null'
